//
// Autogenerated by Thrift Compiler (@PACKAGE_VERSION@)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;


var ttypes = require('./node_types');
//HELPER FUNCTIONS AND STRUCTURES

GatewayService_getGatewayInfo_args = function(args) {
};
GatewayService_getGatewayInfo_args.prototype = {};
GatewayService_getGatewayInfo_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

GatewayService_getGatewayInfo_args.prototype.write = function(output) {
  output.writeStructBegin('GatewayService_getGatewayInfo_args');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

GatewayService_getGatewayInfo_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
GatewayService_getGatewayInfo_result.prototype = {};
GatewayService_getGatewayInfo_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new ttypes.Gateway();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

GatewayService_getGatewayInfo_result.prototype.write = function(output) {
  output.writeStructBegin('GatewayService_getGatewayInfo_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

GatewayService_updGatewayInfo_args = function(args) {
  this.gateway = null;
  if (args) {
    if (args.gateway !== undefined) {
      this.gateway = args.gateway;
    }
  }
};
GatewayService_updGatewayInfo_args.prototype = {};
GatewayService_updGatewayInfo_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.gateway = new ttypes.Gateway();
        this.gateway.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

GatewayService_updGatewayInfo_args.prototype.write = function(output) {
  output.writeStructBegin('GatewayService_updGatewayInfo_args');
  if (this.gateway !== null && this.gateway !== undefined) {
    output.writeFieldBegin('gateway', Thrift.Type.STRUCT, 1);
    this.gateway.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

GatewayService_updGatewayInfo_result = function(args) {
};
GatewayService_updGatewayInfo_result.prototype = {};
GatewayService_updGatewayInfo_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

GatewayService_updGatewayInfo_result.prototype.write = function(output) {
  output.writeStructBegin('GatewayService_updGatewayInfo_result');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

GatewayService_delGatewayInfo_args = function(args) {
  this.id = null;
  if (args) {
    if (args.id !== undefined) {
      this.id = args.id;
    }
  }
};
GatewayService_delGatewayInfo_args.prototype = {};
GatewayService_delGatewayInfo_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.id = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

GatewayService_delGatewayInfo_args.prototype.write = function(output) {
  output.writeStructBegin('GatewayService_delGatewayInfo_args');
  if (this.id !== null && this.id !== undefined) {
    output.writeFieldBegin('id', Thrift.Type.I32, 1);
    output.writeI32(this.id);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

GatewayService_delGatewayInfo_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
GatewayService_delGatewayInfo_result.prototype = {};
GatewayService_delGatewayInfo_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.BOOL) {
        this.success = input.readBool();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

GatewayService_delGatewayInfo_result.prototype.write = function(output) {
  output.writeStructBegin('GatewayService_delGatewayInfo_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.BOOL, 0);
    output.writeBool(this.success);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

GatewayServiceClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this._seqid = 0;
    this._reqs = {};
};
GatewayServiceClient.prototype = {};
GatewayServiceClient.prototype.seqid = function() { return this._seqid; }
GatewayServiceClient.prototype.new_seqid = function() { return this._seqid += 1; }
GatewayServiceClient.prototype.getGatewayInfo = function(callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_getGatewayInfo();
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_getGatewayInfo();
  }
};

GatewayServiceClient.prototype.send_getGatewayInfo = function() {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('getGatewayInfo', Thrift.MessageType.CALL, this.seqid());
  var args = new GatewayService_getGatewayInfo_args();
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

GatewayServiceClient.prototype.recv_getGatewayInfo = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new GatewayService_getGatewayInfo_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('getGatewayInfo failed: unknown result');
};
GatewayServiceClient.prototype.updGatewayInfo = function(gateway, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_updGatewayInfo(gateway);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_updGatewayInfo(gateway);
  }
};

GatewayServiceClient.prototype.send_updGatewayInfo = function(gateway) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('updGatewayInfo', Thrift.MessageType.CALL, this.seqid());
  var args = new GatewayService_updGatewayInfo_args();
  args.gateway = gateway;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

GatewayServiceClient.prototype.recv_updGatewayInfo = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new GatewayService_updGatewayInfo_result();
  result.read(input);
  input.readMessageEnd();

  callback(null)
};
GatewayServiceClient.prototype.delGatewayInfo = function(id, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_delGatewayInfo(id);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_delGatewayInfo(id);
  }
};

GatewayServiceClient.prototype.send_delGatewayInfo = function(id) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('delGatewayInfo', Thrift.MessageType.CALL, this.seqid());
  var args = new GatewayService_delGatewayInfo_args();
  args.id = id;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

GatewayServiceClient.prototype.recv_delGatewayInfo = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new GatewayService_delGatewayInfo_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('delGatewayInfo failed: unknown result');
};
GatewayServiceProcessor = exports.Processor = function(handler) {
  this._handler = handler
}
GatewayServiceProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}

GatewayServiceProcessor.prototype.process_getGatewayInfo = function(seqid, input, output) {
  var args = new GatewayService_getGatewayInfo_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.getGatewayInfo.length === 0) {
    Q.fcall(this._handler.getGatewayInfo)
      .then(function(result) {
        var result = new GatewayService_getGatewayInfo_result({success: result});
        output.writeMessageBegin("getGatewayInfo", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("getGatewayInfo", Thrift.MessageType.EXCEPTION, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.getGatewayInfo(function (err, result) {
      if (err == null) {
        var result = new GatewayService_getGatewayInfo_result((err != null ? err : {success: result}));
        output.writeMessageBegin("getGatewayInfo", Thrift.MessageType.REPLY, seqid);
      } else {
        var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("getGatewayInfo", Thrift.MessageType.EXCEPTION, seqid);
      }
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

GatewayServiceProcessor.prototype.process_updGatewayInfo = function(seqid, input, output) {
  var args = new GatewayService_updGatewayInfo_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.updGatewayInfo.length === 1) {
    Q.fcall(this._handler.updGatewayInfo, args.gateway)
      .then(function(result) {
        var result = new GatewayService_updGatewayInfo_result({success: result});
        output.writeMessageBegin("updGatewayInfo", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("updGatewayInfo", Thrift.MessageType.EXCEPTION, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.updGatewayInfo(args.gateway, function (err, result) {
      if (err == null) {
        var result = new GatewayService_updGatewayInfo_result((err != null ? err : {success: result}));
        output.writeMessageBegin("updGatewayInfo", Thrift.MessageType.REPLY, seqid);
      } else {
        var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("updGatewayInfo", Thrift.MessageType.EXCEPTION, seqid);
      }
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

GatewayServiceProcessor.prototype.process_delGatewayInfo = function(seqid, input, output) {
  var args = new GatewayService_delGatewayInfo_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.delGatewayInfo.length === 1) {
    Q.fcall(this._handler.delGatewayInfo, args.id)
      .then(function(result) {
        var result = new GatewayService_delGatewayInfo_result({success: result});
        output.writeMessageBegin("delGatewayInfo", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("delGatewayInfo", Thrift.MessageType.EXCEPTION, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.delGatewayInfo(args.id, function (err, result) {
      if (err == null) {
        var result = new GatewayService_delGatewayInfo_result((err != null ? err : {success: result}));
        output.writeMessageBegin("delGatewayInfo", Thrift.MessageType.REPLY, seqid);
      } else {
        var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("delGatewayInfo", Thrift.MessageType.EXCEPTION, seqid);
      }
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

